-- V12: categories — the canonical transaction categories the ML model knows.
-- `code` MUST match the model's category_list exactly (it's sent to /predict).
-- `display_name` is a friendly label for dropdowns and UI.

CREATE TABLE categories (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(60)  NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_categories_code UNIQUE (code)
);

-- Seed with the model's exact category list (do not change these codes).
INSERT INTO categories (code, display_name) VALUES
    ('entertainment',   'Entertainment'),
    ('food_dining',     'Food & Dining'),
    ('gas_transport',   'Gas & Transport'),
    ('grocery_net',     'Grocery (online)'),
    ('grocery_pos',     'Grocery (in-store)'),
    ('health_fitness',  'Health & Fitness'),
    ('home',            'Home'),
    ('kids_pets',       'Kids & Pets'),
    ('misc_net',        'Miscellaneous (online)'),
    ('misc_pos',        'Miscellaneous (in-store)'),
    ('personal_care',   'Personal Care'),
    ('shopping_net',    'Shopping (online)'),
    ('shopping_pos',    'Shopping (in-store)'),
    ('travel',          'Travel');