-- V13: merchants — real payable merchants with a location and contact handles.
-- category_id references the canonical categories table (referential integrity);
-- the linked category's `code` is what gets sent to the ML model at scoring time.

CREATE TABLE merchants (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255)  NOT NULL,
    email        VARCHAR(255),
    phone        VARCHAR(40),
    category_id  BIGINT        NOT NULL,
    lat          NUMERIC(9, 6) NOT NULL,
    lon          NUMERIC(9, 6) NOT NULL,
    active       BOOLEAN       NOT NULL DEFAULT true,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT fk_merchants_category FOREIGN KEY (category_id)
        REFERENCES categories (id),
    CONSTRAINT uq_merchants_email UNIQUE (email),
    CONSTRAINT uq_merchants_phone UNIQUE (phone)
);

CREATE INDEX idx_merchants_category ON merchants (category_id);
CREATE INDEX idx_merchants_active ON merchants (active);

CREATE TRIGGER trg_merchants_updated_at
    BEFORE UPDATE ON merchants
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();