-- V3: accounts
-- One user can hold multiple bank accounts. balance/amount use NUMERIC,
-- never float, so money is exact.

CREATE TABLE accounts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT         NOT NULL,
    account_number VARCHAR(34)    NOT NULL,
    balance        NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    status         VARCHAR(20)    NOT NULL DEFAULT 'ACTIVE',
    created_at     TIMESTAMPTZ    NOT NULL DEFAULT now(),

    CONSTRAINT fk_accounts_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_accounts_account_number UNIQUE (account_number),
    CONSTRAINT chk_accounts_status CHECK (status IN ('ACTIVE', 'FROZEN')),
    CONSTRAINT chk_accounts_balance CHECK (balance >= 0)
);

CREATE INDEX idx_accounts_user_id ON accounts (user_id);
