-- V4: merchant_categories
-- Lookup table used by Layer 3 (context-aware) scoring. The consumer looks up
-- a merchant by name to find its risk_level / risk_score.

CREATE TABLE merchant_categories (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_name VARCHAR(255)  NOT NULL,
    category      VARCHAR(60)   NOT NULL,
    risk_level    VARCHAR(20)   NOT NULL,
    risk_score    NUMERIC(4, 3) NOT NULL DEFAULT 0.000,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT uq_merchant_categories_name UNIQUE (merchant_name),
    CONSTRAINT chk_merchant_risk_level CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT chk_merchant_risk_score CHECK (risk_score >= 0 AND risk_score <= 1)
);

CREATE INDEX idx_merchant_categories_category ON merchant_categories (category);

CREATE TRIGGER trg_merchant_categories_updated_at
    BEFORE UPDATE ON merchant_categories
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
