-- V5: user_profiles
-- One row per user (Layer 2 scoring). JSON arrays stored as JSONB so they're
-- queryable/indexable later. UNIQUE(user_id) enforces one profile per user.

CREATE TABLE user_profiles (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                   BIGINT         NOT NULL,
    total_transactions        INTEGER        NOT NULL DEFAULT 0,
    avg_amount                NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    max_amount                NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    large_purchase_count      INTEGER        NOT NULL DEFAULT 0,
    large_purchase_categories JSONB          NOT NULL DEFAULT '[]'::jsonb,
    last_known_device         VARCHAR(255),
    home_lat                  NUMERIC(9, 6),
    home_lon                  NUMERIC(9, 6),
    known_locations           JSONB          NOT NULL DEFAULT '[]'::jsonb,
    has_late_night_history    BOOLEAN        NOT NULL DEFAULT FALSE,
    account_age_days          INTEGER        NOT NULL DEFAULT 0,
    profile_maturity          VARCHAR(20)    NOT NULL DEFAULT 'NEW',
    created_at                TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at                TIMESTAMPTZ    NOT NULL DEFAULT now(),

    CONSTRAINT fk_user_profiles_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_user_profiles_user UNIQUE (user_id),
    CONSTRAINT chk_profile_maturity
        CHECK (profile_maturity IN ('NEW', 'DEVELOPING', 'MATURE'))
);

CREATE TRIGGER trg_user_profiles_updated_at
    BEFORE UPDATE ON user_profiles
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
