-- V6: transactions
-- Core table. Holds raw transaction data + the three scoring outputs
-- (isolation_forest_score, xgboost_probability, fraud_score) and the decision
-- (risk_level). Scores/risk_level are NULL until the ML pipeline runs.
-- merchant_category is a denormalized snapshot of the category at txn time.

CREATE TABLE transactions (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id             BIGINT           NOT NULL,
    amount                 NUMERIC(15, 2)   NOT NULL,
    merchant               VARCHAR(255)     NOT NULL,
    merchant_category      VARCHAR(60),
    location_lat           NUMERIC(9, 6),
    location_lon           NUMERIC(9, 6),
    device_id              VARCHAR(255),
    ip_address             VARCHAR(45),               -- fits IPv6
    transaction_time       TIMESTAMPTZ      NOT NULL DEFAULT now(),
    status                 VARCHAR(20)      NOT NULL DEFAULT 'PENDING',
    fraud_score            DOUBLE PRECISION,          -- final blended score 0..1
    isolation_forest_score DOUBLE PRECISION,          -- raw anomaly score
    xgboost_probability    DOUBLE PRECISION,          -- supervised prob 0..1
    risk_level             VARCHAR(20),
    is_flagged             BOOLEAN          NOT NULL DEFAULT FALSE,
    user_confirmed         BOOLEAN,                   -- NULL = no response yet
    reviewed_by            BIGINT,                    -- admin who reviewed it
    created_at             TIMESTAMPTZ      NOT NULL DEFAULT now(),

    CONSTRAINT fk_transactions_account
        FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE,
    CONSTRAINT fk_transactions_reviewer
        FOREIGN KEY (reviewed_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT chk_transactions_status
        CHECK (status IN ('PENDING', 'APPROVED', 'FLAGGED', 'BLOCKED')),
    CONSTRAINT chk_transactions_risk_level
        CHECK (risk_level IS NULL OR risk_level IN ('GREEN', 'YELLOW', 'ORANGE', 'RED')),
    CONSTRAINT chk_transactions_amount CHECK (amount > 0)
);

CREATE INDEX idx_transactions_account_id ON transactions (account_id);
CREATE INDEX idx_transactions_transaction_time ON transactions (transaction_time);
CREATE INDEX idx_transactions_status ON transactions (status);
CREATE INDEX idx_transactions_risk_level ON transactions (risk_level);

-- Composite index for velocity checks:
-- "how many txns for this account in the last N minutes?"
CREATE INDEX idx_transactions_account_time
    ON transactions (account_id, transaction_time DESC);
