-- V7: fraud_alerts
-- One row per alert dispatched (via RabbitMQ). Linked to the transaction that
-- triggered it. resolved/resolved_by/resolution_notes drive the admin
-- alert-management workflow.

CREATE TABLE fraud_alerts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id   BIGINT       NOT NULL,
    risk_level       VARCHAR(20)  NOT NULL,
    alert_type       VARCHAR(20)  NOT NULL,
    notified_at      TIMESTAMPTZ,
    resolved         BOOLEAN      NOT NULL DEFAULT FALSE,
    resolved_by      BIGINT,
    resolution_notes TEXT,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_fraud_alerts_transaction
        FOREIGN KEY (transaction_id) REFERENCES transactions (id) ON DELETE CASCADE,
    CONSTRAINT fk_fraud_alerts_resolver
        FOREIGN KEY (resolved_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT chk_fraud_alerts_risk_level
        CHECK (risk_level IN ('GREEN', 'YELLOW', 'ORANGE', 'RED')),
    CONSTRAINT chk_fraud_alerts_alert_type
        CHECK (alert_type IN ('EMAIL', 'SMS', 'PUSH'))
);

CREATE INDEX idx_fraud_alerts_transaction_id ON fraud_alerts (transaction_id);
CREATE INDEX idx_fraud_alerts_risk_level ON fraud_alerts (risk_level);
CREATE INDEX idx_fraud_alerts_resolved ON fraud_alerts (resolved);
